### ISSUE TITLE
Parser doesn't count the lines correctly on Windows

### ISSUE THREAD

**Issue by Arcanemagus** [RedCoolBeans/dockerlint#4]
I got the following output when attempting to run the tests  for `dockerlint` v0.1.4 on Windows:

```text
  1) parser should count the lines correctly:

      AssertionError: expected 6 to deeply equal 8
      + expected - actual

      -6
      +8

    at Assertion.assertEqual (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\chai\lib\chai\core\assertions.js:439:19)
    at Assertion.ctx.(anonymous function) [as equal] (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\chai\lib\chai\utils\addMethod.js:40:25)
    at Context.<anonymous> (C:\Users\Landon Abney\Documents\GitHub\dockerlint\test\parserTest.coffee:45:68)
    at callFn (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runnable.js:286:21)
    at Test.Runnable.run (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runnable.js:279:7)
    at Runner.runTest (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:421:10)
    at C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:528:12
    at next (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:341:14)
    at C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:351:7
    at next (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:283:14)
    at Immediate._onImmediate (C:\Users\Landon Abney\Documents\GitHub\dockerlint\node_modules\mocha\lib\runner.js:319:5)
```

I'm guessing this is a combination of two things:

*   There is no `.gitattributes` file specifying the line endings for files in this repository, so on Windows it is defaulting to `CRLF`.
*   The parser may not be counting CRLF lines properly?

This test works correctly on my Ubuntu virtual machine.

_Note:_
As `make` isn't defined by default I was simply running the following manually:
```ShellSession
.\node_modules\.bin\mocha --require coffee-script/register --require chai --reporter spec --compilers coffee:coffee-script/register test/*.coffee
```

**Comment by jasperla** [comment]
Thanks for this ticket and #5 , I'll handle them shortly.
